spring:
  flyway:
    out-of-order: true
    baseline-on-migrate: true
  datasource:
    url: ${USER_DATABASE:}
    username: ${USERNAME:}
    password: ${USER_PASSWORD:}
  freemarker:
    template-loader-path: "classpath:templates"
    suffix: ".ftl"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  api-docs:
    path : '/api-docs'
    swagger-ui:
      path: '/swagger-ui.html'