spring:
  flyway:
    out-of-order: true
    baseline-on-migrate: true
  datasource:
    url: ${USER_DATABASE:}
    username: ${USERNAME:}
    password: ${USER_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true