CREATE SEQUENCE IF NOT EXISTS user_seq INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS user
(
    id INT CHECK (id > 0) NOT NULL DEFAULT NEXTVAL ('USER_seq'),
    username VARCHAR(20) UNIQUE NOT NULL,
    password VARCHAR(30) UNIQUE NOT NULL,
    first_name VARCHAR(20) NOT NULL,
    surname VARCHAR(20) NOT NULL,
    email VARCHAR(40) UNIQUE NOT NULL,
    address VARCHAR(40) NOT NULL,
    role TEXT NOT NULL
);

ALTER TABLE user
    ADD CONSTRAINT username UNIQUE (username);
ALTER TABLE user
    ADD CONSTRAINT email UNIQUE (email);
ALTER TABLE user
    ADD CONSTRAINT password UNIQUE (password);